# ───────────────────────────────────────────────
#                 Dataset Input
#  Choose ONE of the two options below for your data.
# ───────────────────────────────────────────────
dataset:
  # --- Option A: Use a single, pre-combined file (Recommended) ---
  # Uncomment 'input_file' if you have one file with positions, forces, and energy.
  # input_file: "dataset_pos_frc_ev.xyz"

  # --- Option B: Auto combine separate position and force files ---
  # Use these lines if your positions and forces are in two different files.
   pos_file: "HgTe-pos-1.xyz"
   frc_file: "HgTe-frc-1.xyz"
  
   output_prefix: "consolidated_dataset" 
   
   sizes: [200,500] # Number of structures to include in each subset (for training/validation splits)
   create_random_baseline: true
   
   plot_elbow: true
  #  elbow_k_values: [10, 20, 150, 200, 1000, 1500] # If elbow_k_values is set, then: elbow_max_k is effectively ignored for list generation
   elbow_max_k: 5000  # Used only when plot_elbow: true and elbow_k_values is not provided, elbow_max_k: 1000 means auto list stops at 1000

   auto_add_elbow_size: true # If true, automatically add the elbow-selected size to the 'sizes' list
   max_auto_elbow_size: 2000 # Maximum allowed size for auto-added elbow subset (to prevent adding excessively large subsets)

   max_cluster_map_k: 1000 # Maximum k value for generating the cluster map 
   elbow_selection_method: "knee"
   
  # Subset counts (number of structures from each method)
   subset_counts:
     MD: 4036  # Structures obtained from Molecular Dynamics (MD) simulation 
   contamination: 0.05 # Fraction of outliers removed by Isolation Forest 
   n_sets: 2 # Number of random subsets to create (for training/validation splits)
   seed: 0 # seed for n_sets allocation (for reproducibility)
# ───────────────────────────────────────────────
# Optional SOAP descriptor settings
# (You can safely remove this section to let MLFF-QD
#  auto-detect species and use default SOAP parameters)
# ───────────────────────────────────────────────
SOAP: 
   species: ["Hg", "Cl", "Te"] 
   r_cut: 12.0 
   n_max: 7 
   l_max: 3 
   sigma: 0.1 
   periodic: False
   sparse: False